version: "2"

services:
  network-server:
    build: ./network-server
    restart: unless-stopped
    depends_on: 
      - mosquitto
      - postgresql
      - redis
      - application-server

  application-server:
    build: ./application-server
    restart: unless-stopped
    depends_on: 
      - mosquitto
      - postgresql
      - redis
    ports:
      - 8080:8080

    
  gateway-bridge:
    build: ./gateway-bridge
    restart: unless-stopped
    depends_on: 
      - mosquitto
    ports:
      - 1700:1700/udp

  packet_forwarder:
    build: ./packet_forwarder
    restart: unless-stopped
    env_file: ./packet_forwarder.env
    privileged: true
    depends_on: 
      - gateway-bridge

  postgresql:
    build: ./postgresql
    restart: unless-stopped
    volumes:
      - postgresqldata:/var/lib/postgresql/data

  redis:
    image: arm32v7/redis:5-alpine
    restart: unless-stopped
    volumes:
      - redisdata:/data

  mosquitto:
    image: arm32v6/eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883

volumes:
  postgresqldata:
  redisdata:
