version: "2"

services:
  packet_forwarder:
    build: ./ttn-resin-gateway-rpi
    restart: unless-stopped
    env_file: ./packet_forwarder.env

  postgresql:
    build: ./postgresql
    restart: unless-stopped
    volumes:
      - postgresqldata:/var/lib/postgresql/data

  redis:
    image: arm32v7/redis:5-alpine
    restart: unless-stopped
    volumes:
      - redisdata:/data

  mosquitto:
    image: arm32v6/eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883

volumes:
  postgresqldata:
  redisdata:
