version: "2"

services:
  application-server:
    build: ./application-server
    restart: unless-stopped
    depends_on: 
      - mosquitto
      - postgresql
      - redis
    ports:
      - 8080:8080

  network-server:
    build: ./network-server
    restart: unless-stopped
    depends_on: 
      - mosquitto
      - postgresql
      - redis
      - application-server

  packet_forwarder:
    build: ./packet_forwarder
    restart: unless-stopped
    environment:
      - SERVER_1_ENABLED=true
      - SERVER_1_ADDRESS=gateway-bridge
      - SERVER_1_PORTUP=1700
      - SERVER_1_PORTDOWN=1700
      - SERVER_1_DOWNLINK=true
      
    privileged: true
    depends_on: 
      - gateway-bridge

  gateway-bridge:
    build: ./gateway-bridge
    restart: unless-stopped
    depends_on: 
      - mosquitto
    ports:
      - 1700:1700/udp

  postgresql:
    build: ./postgresql
    restart: unless-stopped
    volumes:
      - postgresqldata:/var/lib/postgresql/data

  redis:
    image: arm32v7/redis:5-alpine
    restart: unless-stopped
    volumes:
      - redisdata:/data

  mosquitto:
    image: arm32v6/eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883

volumes:
  postgresqldata:
  redisdata:
